public class Main {

    public static void main(String[] args) {
        Battery mc96 = new Battery("VTec", "MC96", 14.4, 6.6, 0.55, 72, 97, 51.5);
        Battery mc60 = new Battery("VTec", "MC60", 14.4, 4.2, 0.35, 52, 77, 40.5);
        Battery mdPL140 = new Battery("BowserPower", "MD-PL140", 14.4, 9.9, 1.18, 89, 119, 85);
        Battery zlD72 = new Battery("MT-Dell Tech", "ZL-D72", 7.2, 9.9, 1.18, 38, 80, 70);

        // Simply put, hashCode() returns an integer value, generated by a hashing algorithm.
        // Objects that are equal (according to their equals()) must return the same hash code.
        // HashCode() is inherited from the Object class

        System.out.println("reference to mc96 -> " + Integer.toHexString(mc96.hashCode()));
        System.out.println(mc96);
        System.out.println(mc60);
        System.out.println(mdPL140);
        System.out.println(zlD72);
    }
}

class Battery{
    public String manufacturer;
    public String model;
    public double voltage;
    public double ampHours;
    public double weightKg;
    public double[] dimensionMm;

    public Battery(String manufacturer,
                   String model,
                   double voltage,
                   double ampHours,
                   double weightKg,
                   double wMm,
                   double hMm,
                   double dMm){
        this.manufacturer = manufacturer;
        this.model = model;
        this.voltage = voltage;
        this.ampHours = ampHours;
        this.weightKg = weightKg;
        this.dimensionMm = new double[]{wMm, hMm, dMm};
    }

    public double getPowerCapacity(){
        return ampHours * voltage;
    }

    public String toString(){
        String hash = Integer.toHexString(hashCode());
        return "Battery details- manufacturer: " + manufacturer + ", model: " + model + ", hash: " + hash;
    }
}
